spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sfbookdb
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  h2:
    console:
      enabled: false

logging:
  level:
    root: INFO
    com.sfcollection: INFO
  file:
    name: logs/application.log