spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:sfbookdb}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
  h2:
    console:
      enabled: false

server:
  port: ${PORT:8080}
  servlet:
    context-path: /

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000 # 24 hours in milliseconds

springdoc:
  api-docs:
    enabled: ${ENABLE_API_DOCS:false}
  swagger-ui:
    enabled: ${ENABLE_SWAGGER_UI:false}

logging:
  level:
    root: INFO
    com.sfcollection: INFO
  file:
    name: /var/log/sfbookcollection/application.log

management:
  endpoints:
    web:
      exposure:
        include: health,metrics,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
  info:
    git:
      enabled: true
  health:
    diskspace:
      enabled: true
    db:
      enabled: true